# Semaphore 1.0 uses this default config for the ubuntu1804 VM running the MySQL service:
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: semaphoredb
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: goggles_development

test:
  <<: *default
  database: goggles_test
