default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV.fetch("DATABASE_NAME") { 'goggles' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
